### ISSUE TITLE
Health check failed with extension v1.1.1850.1

### ISSUE THREAD

**Issue by Largelos** [Azure-Samples/azure-mfa-nps-extension-health-check#21]
Version and registry check failed with latest NPS extension version:
<!DOCTYPE HTML>
<HTML xmlns="http://www.w3.org/1999/xhtml"><HEAD></HEAD><BODY><TABLE><TBODY><TR><TD>Checking if the current installed MFA NPS Extension Version is the latest</TD><TD>Test Failed</TD><TD>Make sure to Upgrade to the latest version</TD><TD>Current installed MFA Version is: 1.1.1850.1</TD></TR><TR><TD>Checking if NPS Service is Running</TD><TD>Test Passed</TD><TD>N/A</TD><TD>N/A</TD></TR><TR><TD>Checking if Azure MFA SPN is Exist in the tenant</TD><TD>Test Passed</TD><TD>N/A</TD><TD>N/A</TD></TR><TR><TD>Checking if Azure MFA SPN is Enabled in the tenant</TD><TD>Test Passed</TD><TD>N/A</TD><TD>N/A</TD></TR><TR><TD>Checking if Auth\Extension Registries have the correct values</TD><TD>Test Passed</TD><TD>N/A</TD><TD>N/A</TD></TR><TR><TD>Checking Other MFA regstries status</TD><TD>Test Failed</TD><TD>Re-register the MFA extension or Consult MS Support</TD><TD>N/A</TD></TR></TBODY></TABLE></BODY></HTML>

**Comment by Lawike2** [comment]
I am having the same experience. Any workaround?

**Comment by nathanmcnulty** [comment]
This issue occurs because the script is checking the version number from the Microsoft Downloads website, and it looks like they often forget to update the version number there causing a mismatch.

The script was recently updated to account for this (passes if version installed is newer than the website):
https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/commit/33050825ad30ab7fbe45b3bb369cf836f32d944a

**Comment by Justinha** [comment]
@nathanmcnulty thank you!
