### ISSUE TITLE
Script Reporting SPN Missing and User not licensed

### ISSUE THREAD

**Issue by NeoZer01** [Azure-Samples/azure-mfa-nps-extension-health-check#53]
Is there a problem with the script in regard to the SPN test and user license test?  I rant this in a customer environment that has a new install and the tool is reporting the MFA extension SPN is not in the tenant and the user is not MFA licensed even though they have a P1 license.

please reach out to me if you need additional info, alias:weham

**Comment by miguel-s-ferreira** [comment]
After checking what was the context of current situation, it was evidence that SPN for Azure Multi-Factor Auth Client was not created and it could be fixed by following this documentation:

- https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension#how-to-fix-the-error-service-principal-was-not-found-while-running-azuremfanpsextnconfigsetupps1-script [https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension#how-to-fix-the-error-service-principal-was-not-found-while-running-azuremfanpsextnconfigsetupps1-script](url)

Related with user not having a valid license, it should be checked which were the license assigned to user and retrieved by script.

**Comment by Justinha** [comment]
@miguel-s-ferreira thanks for your help! #please-close
